* 归属于母公司所有者净利润
** 公式
母公司利润 + sigma(子公司利润*对子公司持股比例)
** 例子
比如，某一上市公司实现净利润100万元，
其持有70%股权的子公司实现净利润50万元。
假设该上市公司没有其他子公司，且母子公司之间没有净利润的抵销业务，
则，母公司合并净利润150万元（100 + 50），
而该上市公司拥有子公司净利润的份额应当为35万元（50 * 70%），
由此，母公司总计实现净利润135万元（100 + 35），
该净利润应当归属于母公司的股东。
除此之外，子公司实现的净利润的剩余部分15万元（50 - 35），
归属子公司其他股东（也就是通常所说的“少数股东”）所有。


* 归属于母公司的所有者权益
作者：易懂财税
链接：https://www.zhihu.com/question/372169609/answer/2434537358
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
首先要了解几个概念：合并资产负债表，少数股东权益，归属母公司的所有者权益，以及相关等式。
1. 合并资产负债表：股权上有密切关系的两个或两个以上的独立企业，
   作为一个整体而合并编制的资产负债表，用来反映控股公司及其附属公司合并的财务状况。
2. 归属母公司的所有者权益：反映合并报表中公司集团的所有者权益中归属于母公司所有者权益的部分。
   母公司在编制合并报表时，要把他的控股子公司中所属的权益加上去。
   归属母公司的所有者权益=母公司自己的所有者权益+母公司可以按对子公司的持股比例享有子公司的股东权益。
3. 少数股东权益：简称少数股权。对于子公司的所有者权益，其中有一部分是属于母公司所有，
   其余一些属外界其他股东所有，属于外部的这些股权称为少数股东权益。 
4. 公式：
   合并报表所有者权益合计=合并报表中归属于母公司所有者权益+合并报表中少数股东权益
   =合并报表中总资产-合并报表中总负债
   个别报表中所有者权益
   =个别报表中总资产-个别报表中总负债
5. 例子
   举个例子解释一下归属于母公司的所有者权益以及少数股东权益：
   A公司当年所有者权益100万元， A公司持有B公司60%的股份，
   今年B的股东权益为10万元。编制合并资产负债表时：
   对于子公司的所有者权益，10x60%=6万元（60%的权益）计算到“归属于母公司所有者的权益”里，
   剩下40%是其他人持有的，与母公司的股东无关，计入到“少数股东权益”里。
   合并报表所有者权益
   =合并报表归属于母公司所有者权益+合并报表少数股东权益
   =（母公司自己的所有者权益+母公司可以按对子公司的持股比例享有子公司的股东权益）+合并报表少数股东权益
   =（100+6）+4=110万元
   注意：只有在合并报表时候，才会涉及到“少数股东权益”和“归属于母公司的所有者权益”。
   个别报表里面只有“所有者权益”。

* 企业的市值与总资产是什么关系？
** A1
市值是指二级市场对公司发行在外的股票的公允价值
这种溢价或者折价是不会体现在公司的资产负债报表里面的
市值根据股价也就是最新的交易价格确定
2级市场交易者之间的交易上市公司不会直接参与

这样一来 即使想做进报表 credit一个权益 debit啥？

** A2
我的理解是：
把苹果公司比喻成母鸡的话，总资产是把母鸡杀了卖肉能卖多少钱，
股票市值是不杀鸡养着下蛋在未来能赚多少钱。

按自由现金流折现理论，公司价值是在未来永续运营前提下，
每年自由现金流的累计折现值，这个值是要大于公司目前资产价值的，
如果市场信息完全公开，这个值应该等于市值，
这个值除以公司目前总资产就等于市盈率


* 合并资产负债表
子公司必须是控股子公司 
否则属于投资收益
